#-------------------------------
# General Site Settings
title: Cecilia Caserotto
logo: 4.png # You can add own logo.
description: Yoga que cura al alma


#-------------------------------
# Author Settings
author:
  name: Cecilia Caserotto
  image: 3.png
  say-hello: <strong>Hola, soy Ceci</strong></br> y quiero invitarte a que vivas una hermosa experiencia de <strong>yoga en la playa</strong>
  bio: Si querés relajarte y conectar con tus deseos te invito a que te sumes a nuestros encuentros. Son clases a la gorra, para todos los géneros y edades, y no hace falta que tengas ningún conocimiento previo. 
  footer: Encontrame todos los días a las 19:30 hs. en El Náutico, parador <strong>AP SURF</strong>.




#-------------------------------
# Contact links
facebook: https://facebook.com/ # Add your Facebook handle
instagram: https://www.instagram.com/ceciliacaserotto/

buttons:
    - text: Quiero sumarme!
      link: https://forms.gle/vNhX3BgzGzs9Yvxy6
    - text: Seguime en Instagram 
      link: https://www.instagram.com/ceciliacaserotto/
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: cecicaserotto # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: ceciliacaserotto # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
